noun = input ("Give me a noun ")
pluralnoun = input ("give me a plural noun ")
verbing = input (" give me a verb ending in ing  ")
pluralnoun2 = input (" give me another plural noun")
city = input (" give me a city ")
pluralnoun3 = input (" give me another plural noun")
adj = input (" give me a adjective")
noun2 = input (" give me another noun")
number = input (" give me a nummber")
noun3 = input (" give me a noun")
adj2 = input (" give me a adjective")
verb = input (" give me a verb")
print (f"In 1981, the u.s. launched the first real Space {noun}. It was named columbia and was piloted by two brave {pluralnoun}. They had practiced {verbing} for two years and were expert {pluralnoun2}. Columbia took off from {city} using its powerful first stage {pluralnoun3} and soared off into the {adj} blue {noun2}. At an altitude of {number} feet, it went into orbit around the {noun3}. For people watching from earth it was a/an {adj2} sight to {verb}")
print ("thank you for participating")
print ("you guys are cool")
print (" I looooove mad libs")
print (" 67")
print ("labubu")
print ("41") 
print ("agartha")
print (" this is so cool")
print (" if you mad it this far, subscibe")
print ("domer")
print (" my mother ate fries")